name: Push docker images to Docker Hub from Feature branches.

on:
  push:
    branches:
      - feature/*/*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      HOST: 0.0.0.0
      NUXT_PUBLIC_PROXY_URL: http://localhost:3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Saving Testing Firebase Keys
        run: |
          mkdir ./tests_setup/keys/
          echo "${{ secrets.E2E_FIREBASE_KEY }}" >> ./test_setup/keys/service-account.json

      - name: Running Test Server
        run: docker compose -f ./tests_setup/server.yml up -d

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run prod

  build_and_push:
    needs: test
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: image_name
        name: Form proper Docker Image Name
        run: |
          DOCKER_TAG=$(echo ${{ github.ref_name }}-${{ github.sha }} | sed 's#/#-#g')
          DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:$DOCKER_TAG"

          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.image_name.outputs.DOCKER_IMAGE }} .

      - name: Logging into Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push into Docker Registry
        run: docker push ${{ steps.image_name.outputs.DOCKER_IMAGE }}
