name: Push docker images to Docker Hub from Feature branches.

on:
  push:
    branches:
      - feature/*/*

jobs:
  build_and_push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - id: image_name
        name: Form proper Docker Image Name
        run: |
          DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:${{ github.ref_name }}-${{ github.sha }}"

          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.image_name.outputs.DOCKER_IMAGE }}

      - name: Logging into Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push into Docker Registry
        run: docker push ${{ steps.image_name.outputs.DOCKER_IMAGE }}
