name: Push docker images to Docker Hub from Feature branches.

on:
  push:
    branches:
      - feature/*/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Saving Testing Firebase Keys
        run: |
          mkdir ./tests_setup/keys/
          echo "${{ secrets.E2E_FIREBASE_KEY }}" >> ./tests_setup/keys/service-account.json

      - name: Running E2E Tests
        run: docker compose -f ./docker-compose.test.yml up --exit-code-from vuevideo_e2e

      - name: Reset Firebase Test Environment
        run: |
          cd firebase_reset
          echo "${{ secrets.E2E_FIREBASE_KEY }}" >> service-account.json

          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service-account-file.json"
          npm i
          npm run delete:users

  build_and_push:
    needs: test
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: image_name
        name: Form proper Docker Image Name
        run: |
          DOCKER_TAG=$(echo ${{ github.ref_name }}-${{ github.sha }} | sed 's#/#-#g')
          DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:$DOCKER_TAG"

          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.image_name.outputs.DOCKER_IMAGE }} .

      - name: Logging into Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push into Docker Registry
        run: docker push ${{ steps.image_name.outputs.DOCKER_IMAGE }}
