name: Push docker images to Docker Hub after Pull Request Merge.

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Saving Testing Firebase Keys
        run: |
          mkdir keys
          echo '${{ secrets.E2E_FIREBASE_KEY }}' >> keys/service-account.json

      - name: Running E2E Tests
        run: docker compose -f ./docker-compose.test.yml up --exit-code-from vuevideo_e2e

      - name: Reset Firebase Test Environment
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/keys/service-account.json"

          cd firebase_reset
          npm i
          npm run delete:users

  build_and_push:
    needs: test
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: image_name
        name: Form proper Docker Image Name
        run: |
          OLD_DOCKER_TAG=$(echo ${{ github.head_ref }}-${{ github.event.pull_request.head.sha }} | sed 's#/#-#g')
          NEW_DOCKER_TAG="stage-${{ github.sha }}"

          OLD_DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:$OLD_DOCKER_TAG"
          NEW_DOCKER_IMAGE="${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/client:$NEW_DOCKER_TAG"

          echo "OLD_DOCKER_IMAGE=$OLD_DOCKER_IMAGE" >> $GITHUB_OUTPUT
          echo "NEW_DOCKER_IMAGE=$NEW_DOCKER_IMAGE" >> $GITHUB_OUTPUT

      - name: Logging into Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tagging and Pushing into Docker Registry
        run: |
          docker pull ${{ steps.image_name.outputs.OLD_DOCKER_IMAGE }}
          docker tag ${{ steps.image_name.outputs.OLD_DOCKER_IMAGE }} ${{ steps.image_name.outputs.NEW_DOCKER_IMAGE }}
          docker push ${{ steps.image_name.outputs.NEW_DOCKER_IMAGE }}
